# Generated by Django 5.2.3 on 2025-08-29 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("page_view", "Page View"),
                            ("search", "Search"),
                            ("download", "Download"),
                            ("export", "Export Data"),
                            ("rate_lookup", "Rate Lookup"),
                            ("insight_view", "Insight View"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("page_url", models.URLField(blank=True, max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_userac_user_id_536d16_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_userac_action_2934d5_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_userac_timesta_ac7f60_idx"
                    ),
                ],
            },
        ),
    ]
